export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';

export const SET_DATA_SOURCE_FILTER = 'SET_DATA_SOURCE_FILTER';
export const SET_CAMPAIGNS_FILTER = 'SET_CAMPAIGNS_FILTER';
